services:
  # сервис статистики
  stats-server:
    build:
      context: .
      dockerfile: stats-service/stats-server/Dockerfile
    container_name: stats-server
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=stats_user
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      # на всякий случай фиксируем биндинг и порт
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=9090
    healthcheck:
      test: [ "CMD-SHELL", "wget -O /dev/null http://localhost:9090/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      stats-db:
        condition: service_healthy

  # база сервиса статистики
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=stats_user
      - POSTGRES_PASSWORD=12345
    volumes:
      - stats-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\"" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # основной сервис
  ewm-service:
    build:
      context: .
      dockerfile: main-service/Dockerfile
    container_name: ewm-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=ewm_user
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - STATS_SERVICE_URL=http://stats-server:9090
      # критично для того, чтобы порт пробросился наружу и wait-for-it увидел localhost:8080
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=8080
      - JAVA_OPTS=-Xmx512m -Xms256m
    healthcheck:
      test: [ "CMD-SHELL", "wget -O /dev/null http://localhost:8080/actuator/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    depends_on:
      ewm-db:
        condition: service_healthy
      stats-server:
        condition: service_healthy

  # база основного сервиса
  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewm_user
      - POSTGRES_PASSWORD=12345
    volumes:
      - ewm-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready  -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  stats-db-data:
  ewm-db-data:
